login_login_admin_users:
    resource: "@LoginLoginBundle/Resources/config/routing/users.yml"
    prefix:   /admin/users

login_login_homepage:
    path:     admin/hello/{name}
    defaults: { _controller: LoginLoginBundle:Default:index }
