admin_users:
    path:     /
    defaults: { _controller: "LoginLoginBundle:Users:index" }

admin_users_show:
    path:     /{id}/show
    defaults: { _controller: "LoginLoginBundle:Users:show" }

admin_users_new:
    path:     /new
    defaults: { _controller: "LoginLoginBundle:Users:new" }

admin_users_create:
    path:     /create
    defaults: { _controller: "LoginLoginBundle:Users:create" }
    methods:  POST

admin_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "LoginLoginBundle:Users:edit" }

admin_users_update:
    path:     /{id}/update
    defaults: { _controller: "LoginLoginBundle:Users:update" }
    methods:  [POST, PUT]

admin_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "LoginLoginBundle:Users:delete" }
    methods:  [POST, DELETE]
