login_login:
    resource: "@LoginLoginBundle/Resources/config/routing.yml"
    prefix:   /

upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
login:
    pattern:   /login
    defaults:  { _controller: LoginLoginBundle:Security:login }
login_check:
    pattern:   /login_check